### ISSUE TITLE
Explicitly typed symbols do not have base functions associated with them

### ISSUE THREAD

**Issue by leios** [JuliaSymbolics/SymbolicUtils.jl#117] opened 2020-07-21 20:43 UTC
The type `Array` is expected to have some functions available like `length(...)` or `reshape!(...)`, but when trying to build a symbolic tree, these functions are not available.

Here, I tried to create 2 arrays (`x`, and `y`) and add `length(y)` to `x`.

```
julia> using SymbolicUtils

julia> @syms x::Array y::Array
(x, y)

julia> z = x^2 .+ length(y)
ERROR: MethodError: no method matching length(::SymbolicUtils.Sym{Array})
Closest candidates are:
  length(::Core.SimpleVector) at essentials.jl:596
  length(::Base.MethodList) at reflection.jl:852
  length(::Core.MethodTable) at reflection.jl:938
  ...
Stacktrace:
 [1] top-level scope at REPL[5]:1

```

**Comment by shashi** [comment] 2020-08-15 21:01
We still have to define methods on array typed variables.

We got started on this in https://github.com/JuliaSymbolics/SymbolicUtils.jl/tree/s/new-array but haven't yet got around to it. Let me know if you need it.

**Comment by shashi** [comment] 2020-08-16 17:33
https://github.com/JuliaSymbolics/SymbolicUtils.jl/pull/123

**Comment by shashi** [comment] 2020-08-16 17:52
I'll close this for now as a duplicate of #16 

maybe the documentation should be made clearer about `::T` though.

**Closed by shashi** 2020-08-16 17:52 UTC
